### ISSUE TITLE
'Shift + Click' or 'Command + Click' won't work when using Karabiner-Elements

### ISSUE THREAD

**Issue by funatsufumiya** [tekezo/Karabiner-Elements#135]
I recently updated my Mac OS X to macOS Sierra 10.12. So I installed Karabiner-Elements instead of Karabiner and Seil, but I couldn't use shift + click or command + click after lauching Karabiner-Elements.

My `~/.karabiner.d/configuration/karabiner.json` file is like below.

``` json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "left_command"
            }
        }
    ]
}
```

Now I removed `Karabiner-Elements.app` but It still won't work, so I also removed `/Library/Application\ Support/org.pqrs/Karabiner-Elements` then shift + click worked properly.

**Comment by wolfcw** [comment]
ack, same problem here. Makes, for example, selecting multiple files in Finder, quite impossible.

**Comment by leira** [comment]
Should have been fixed by https://github.com/tekezo/Karabiner-Elements/issues/5, but I saw this issue again on 0.90.40.

**Comment by bunnyhero** [comment]
i'm experiencing the same thing. shift-click does not work as expected in adobe illustrator, for example: the shift key is essentially ignored when trying to constrain drawing or toggle selection.

here's my configuration file:

```json
{
    "profiles": [
        {
            "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "right_option": "fn"
            }
        }
    ]
}
```

**Comment by leira** [comment]
I just upgraded to Karabiner Elements 0.90.44, shit-click and cmd-click worked again.

**Comment by niieani** [comment]
Looks like #5 is still not fully fixed. Randomly, after many hours of work, it sometimes stops working. Turning Karabiner Elements off and on again fixes it for some time, but it breaks again after a couple of hours.

**Comment by chankonabe** [comment]
I'm still seeing this on 0.90.46, particularly when trying to select multiple files in Finder, i.e. it works for a while but then at some point stops working. Quitting the app works as mentioned.

**Comment by MartinNuc** [comment]
Having this issue.

100% reproducable in Chrome/Safari when trying to open link in a new tab with CMD+click
