### ISSUE TITLE
`/~ and §/± keys incorrectly swapped on Apple Keyboard (vendor 1452 product 545)

### ISSUE THREAD

**Issue by gregrs-uk** [tekezo/Karabiner-Elements#1426]
Many thanks for releasing this software. I have a bug to report as follows:

----

## System details

Karabiner-Elements 12.1.0
MacBook Pro running macOS Sierra 10.12.6
external Apple Keyboard (vendor 1452 product 545)
I use the British keyboard layout

## The problem

The \` and `§` (shifted versions `~` and `±` respectively) are incorrectly swapped around for my external Apple Keyboard (vendor 1452 product 545). This problem goes away if I quit Karabiner-Elements and the keys are correctly mapped for my MacBook's internal keyboard.

## Other symptoms

If I open the Keyboard Viewer, the correct layout of these two keys is displayed. If I then type any key, the layout changes to incorrectly remove the `§/±` key, move the \`/`~` key to its place and widen Shift. The backslash key is also then displayed in the wrong place, above Return instead of to the left of it.

Before typing any key

![before](https://user-images.githubusercontent.com/7353938/40921988-dbdf5440-6808-11e8-9f23-48919c68c1f1.png)

After typing any key

![after](https://user-images.githubusercontent.com/7353938/40921993-dfee160c-6808-11e8-87ef-6961744d27ab.png)

**Comment by gregrs-uk** [comment]
If I open the Keyboard Viewer, the correct layout of these two keys is displayed. If I then type any key, the layout changes to incorrectly remove the `§/±` key, move the \`/`~` key to its place and widen Shift. See below.

Before typing any key

![before](https://user-images.githubusercontent.com/7353938/40921988-dbdf5440-6808-11e8-9f23-48919c68c1f1.png)

After typing any key

![after](https://user-images.githubusercontent.com/7353938/40921993-dfee160c-6808-11e8-87ef-6961744d27ab.png)

**Comment by filipeamoreira** [comment]
I'm having the exact same issue on an external Apple keyboard with vendor id: 1452 and product id: 592.

**Comment by filipeamoreira** [comment]
I have managed to solve my issue by creating a profile for my external keyboard with these simple modifications:
![39169279-827c9e30-4797-11e8-8ef4-1a812d105282](https://user-images.githubusercontent.com/8424/41149722-3b133b68-6b04-11e8-8e92-ab702516401e.png)

**Comment by gregrs-uk** [comment]
Thanks for the workaround, @filipeamoreira. I had looked in that list but didn't think to try `non_us_backslash`.

Of course it would still be great if this could be fixed, though!

**Comment by liricooli** [comment]
I am experiencing something similar:

I have a macbook pro 2016 with mac osx seirra 10.12.6, running a us keyboard.
i'm using a kinesis freestyle with a british layout.

When unplugging the kinesis, the ~ does not work in my internal keyboard, and instead I get `§`.

Restarting the application does not solve this issue.

**Comment by liricooli** [comment]
my current workaround is when switching between the external and internal keyboards - i go to `System Preferences` -> `Keyboard` -> `Change Keyboard Type" and set back the internal keyboard to an `ANSI` type.

**Comment by kassi** [comment]
For all interested here: I'm using KE 12.1.0 and have the same issue with my German layout.
I now kind of fixed it with the above simple modifications (grave -> non_us_backslash and opposite) but chose "Apple Keyboard" as the only target. By that the switch corrects external keyboard and leaves internal one intact. So no need for an extra profile.

**Comment by m67hoff** [comment]
I have the same issue with my German Keyboard (BTW: quit karabiner and the key are  ok - so its defnitly an issue ) - But the   solution above works for me

**Comment by kopach** [comment]
Hi @gregrs-uk. As for the issue reported, have you been using, maybe, this complex modification "[Section sign (§) to Escape]( https://pqrs.org/osx/karabiner/complex_modifications/#section_sign_to_escape)"? If yes – that modification didn't distinguish keyboard types before (I mean, whether it's Apple's one, or not). 
This PR #589 should fix the issue for that complex modification. Now there are 2 rules available:

1. For apple keyboard only
2. for any keyboard

**Comment by gregrs-uk** [comment]
I'm afraid I haven't been using that modification, @kopach. Thanks.

**Comment by zen** [comment]
Thi issue is closed, but apparently the problem exists. I have apple keyboard 1452/545 and this is quite annoying

**Comment by munkychop** [comment]
This is still an issue and should be reopened. I use a British internal keyboard (one simple key mod) and British external keyboard (no key mods). When unplugging the external keyboard, my internal keyboard has the `` ` `` `~` key and `±` `§` key incorrectly swapped.

**Comment by oskarlh** [comment]
@tekezo This is still an issue

**Comment by expelledboy** [comment]
Still an issue on my new Apple Magic Keyboard

**Comment by expelledboy** [comment]
The key registers as `grave_accent_and_tilde` key in Event Viewer however the character that is displayed in the text input box is still this `§` key.

If the "Simple modification" mapping does not work for you:

- System Preferences => Keyboard
- Press "Change Keyboard Type..." Button
- Select `ANSI (United States and others)` option at end of Wizard

**Comment by PavelMelnyk** [comment]
The same issue was reproduced on MacBook Air with `Sequoia 15.0.1` and `Karabiner-Elements 15.0.3`. 😞 
The workaround presented by @filipeamoreira works for me.

**Comment by rileykav** [comment]
Still an issue on macOS 15.1.1 on an m4 MacBook Pro. "Solved" by setting the keyboard layout to ANSI within karabiner elements. It seems setting to ISO first disables all functionality of karabiner to me (my bindings are gone) for 2-3s before making this ` to § swap (and ~ to ±). I think all other keys for me on a dutch layout works fine

**Comment by SkirOwen** [comment]
Same issue on a m3 MacBookPro `macOS 14.6.1 `, `Karabiner-Elements 15.3.0`.
I have a `English UK` layout and never had the issue since I updated Karabiner the other day.

**Comment by PhiloNL** [comment]
Same issue here Dutch keyboard layout, MacOS 15.2 and Karabiner-Elements 15.3.0. Changing the virtual keyboard type to ANSI instead of ISO seems to solve the issue for now.

**Comment by smisch** [comment]
> * System Preferences => Keyboard
> * Press "Change Keyboard Type..." Button
> * Select `ANSI (United States and others)` option at end of Wizard

German keyboard layout here. This suggested solved the issue for me. I had it on "ISO (Europe, Latin America, Middle-East and others)". Setting it to "ANSI" gave me the correct German layout again. 

The current way to find the setting is to open Karabina-Elements Settings, then "Virtual Keyboard" in the menu. It's the radio boxes right at the top. Keep it on ANSI regardless of your local keyboard layout.

**Comment by alexey-cord-tech** [comment]
How on Earth is this closed as 'stale' if there's a fresh complaint at roughly weekly cadence?

(and yes, for the record, it's still an issue  with the latest MacOS and KE as of yesterday)

**Comment by Emprint** [comment]
Still an issue today, was able to implement the exact workaround suggested by @filipeamoreira to switch @ and < keys on an Azerty (French) keyboard, however the workaround suggested by @smisch is better, make sure to select "ANSI" for keyboard type in Karabiner-Elements Settings

<img width="2424" height="1688" alt="Image" src="https://github.com/user-attachments/assets/158b97a1-3e93-45bb-a8d0-aba9ac829827" />

**Comment by josedagama** [comment]
> > * System Preferences => Keyboard
> > * Press "Change Keyboard Type..." Button
> > * Select `ANSI (United States and others)` option at end of Wizard
> 
> German keyboard layout here. This suggested solved the issue for me. I had it on "ISO (Europe, Latin America, Middle-East and others)". Setting it to "ANSI" gave me the correct German layout again.
> 
> The current way to find the setting is to open Karabina-Elements Settings, then "Virtual Keyboard" in the menu. It's the radio boxes right at the top. Keep it on ANSI regardless of your local keyboard layout.

Works like charm!
