### ISSUE TITLE
Karabiner-Elements stopped working after OS X 10.14.2 update (12.1.56)

### ISSUE THREAD

**Issue by Jnmattern** [tekezo/Karabiner-Elements#1664]
Since I updated to OS X 10.14.2, Karabiner-Elements stopped working.
When I run the EventViewer, I get this error message : 
![capture d ecran 2018-12-10 a 15 01 24](https://user-images.githubusercontent.com/4257480/49737628-9f6b5580-fc8d-11e8-8e5e-c5d53b62e2e0.png)

Is there a way to have it working again?

**Comment by Jnmattern** [comment]
Fixed by uninstall-reboot-reinstall, kept all settings & mods.

**Comment by clemsam** [comment]
Hi, did you check with Karabiner-Elements Preferences that in tab "Devices" your keyboard is checked (and recognised correctly)?

**Comment by Jnmattern** [comment]
Hi, yes, it was checked, but for some reason it didn't work anymore until I uninstalled, rebooted and reinstalled it!

Jnm.

--

**Comment by LinusU** [comment]
I'm having a similar problem after upgrading, although the EventViewer works for me, Karabiner Elements still fails to remap `fn` to `left_control`...

**Comment by Jnmattern** [comment]
> I'm having a similar problem after upgrading, although the EventViewer works for me, Karabiner Elements still fails to remap `fn` to `left_control`...
> 
> This happened after upgrading to 10.14.2 today

Did you try reinstalling? Settings are kept so there's no risk 😀

**Comment by LinusU** [comment]
Not yet, will try that next

But I have too many open stuff to reboot right now 😂

**Comment by Xorkle** [comment]
Hi! :) 

Just wanted to report I had the same issue and uninstalling, reboot, installing, and rebooting again worked.

**Comment by LinusU** [comment]
Just rebooting fixed the issue for me, did not have to reinstall :)
