### ISSUE TITLE
0.90.84 breaks Fn keys on external bluetooth keyboard

### ISSUE THREAD

**Issue by hostmaster** [tekezo/Karabiner-Elements#525]
I've got Kinessis Freestyler2 Blue keyboard after upgrade to 0.90.70 all hot keys are broken. for example f4 performs volume up. If karabiner is quited everything works as expected.
My config is simple
```
{
    "profiles": [
        {
             "name": "Default profile",
            "selected": true,
            "simple_modifications": {
                "caps_lock": "f19"
            }
        }
    ]
}
```

**Comment by wjakob** [comment]
Same here -- brightness up/down does not work anymore on my apple bluetooth keyboard. The capslock key LED is permanently lit up. I'm using the standard config that maps caps lock to escape.

**Comment by tekezo** [comment]
@hostmaster I guess your keyboard is not sending properly function key events in order to simulate macOS function keys. (eg. your physical f4 key sends f12 key events)
Please modify the function key mapping in Function Keys tab in Karabiner-Element Preferences.

**Comment by tekezo** [comment]
The brightness up/down highly depends on the display hardware.
Please upgrade to v0.90.72 and try the `apple_display_brightness_decrement` and `apple_display_brightness_increment` in Function Keys tab.

![161231-0002](https://cloud.githubusercontent.com/assets/659178/21577965/ad4683f6-cfb1-11e6-9e12-e99fb6e25d6d.png)

About the caps lock LED, if the caps lock LED is lit up before Karabiner-Elements start, Karabiner-Elements keep the state.

**Comment by hostmaster** [comment]
@tekezo it is not  the case, all keys are working properly if karabiner-elements is not running. 

after upgrade to 0.90.72 Fn keys are functional again but mapping `cap lock` -> `f19` does not work now. 

I followed the article [CapsLock input source switching in Mac OS X](https://nolar.info/capslock-input-source-switching-in-macosx/) but seems like now cap lock does not generate any events 

and the same thing has happened for internal keyboard as well

**Comment by tekezo** [comment]
@hostmaster Due to the macOS limitation, Karabiner-Elements have to change f1-f12 keys to media control by itself. So, Karabiner-Elements changes f12 key event to volume up.
Some Mac Model keyboards sends improper key event for physical f3 and f4 keys because macOS has interpreted f10-f12 key events to mission control, dashboard.
These combination causes your issue.

About caps lock key, there are any error message in Log tab of Karabiner-Element Preferences?

**Comment by hostmaster** [comment]
@tekezo volume up/down, dashboard and mission control work as expected with 0.90.72

there are warnings in Log tab
```
[2017-01-01 13:13:32.000] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.
[2017-01-01 13:13:33.002] [warning] [grabber] event_manipulator_ is not ready. (virtual_hid_device_client is not ready) Please wait for a while.
```

**Comment by tekezo** [comment]
@hostmaster Thank you for information!

There is an issue that Karabiner-Elements requires to reboot after install (eg #527 )
But I have not succeed to reproduce the issue yet.

I would like to know the result of this command in Terminal.
```
sudo kextload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
```

**Comment by hostmaster** [comment]
@tekezo thank you the output is below
```
sudo kextload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
Password:
/Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext failed to load - (libkern/kext) not found; check the system/kernel logs for errors or try kextutil(8).
```

from the console 
```
default	16:35:27.540884 +0300	sudo	    igor : TTY=ttys004 ; PWD=/Users/igor ; USER=root ; COMMAND=/sbin/kextload /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext
error	16:35:27.545217 +0300	sandboxd	SandboxViolation: bird(377) deny file-read-data /Users/igor [Duplicate; no report will be generated.]
default	16:35:27.547701 +0300	opendirectoryd	Client: <private>, UID: 0, EUID: 0, GID: 0, EGID: 0
default	16:35:27.549125 +0300	kextd	Error: Kext /Library/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.kext - not found/unable to create.
error	16:35:27.549981 +0300	sandboxd	SandboxViolation: bird(377) deny file-read-data /Users/igor [Duplicate; no report will be generated.]
```
I'm not rebooting the system in case you need more details.

**Comment by tekezo** [comment]
@hostmaster Thank you for information.
It's very strange, the installation post process seems to be not executed for some reason...
Could you install Karabiner-Elements again?

**Comment by hostmaster** [comment]
@tekezo after some re-tries and system reboot the module is loaded finally. However it breaks hotkeys (Fn) keys again. Some Fn keys has no effect now (Dock, Volume) 

From the EventViewer. Karabiner is running.  I pressed MissionControl key (F3)
![eventviewer 2017-01-02 14-02-43](https://cloud.githubusercontent.com/assets/197788/21588134/caa59650-d0f4-11e6-9b7b-bead194890aa.jpg)

From the EventViewer. Karabiner is running.  I pressed Dashboard key (F4)
![eventviewer 2017-01-02 14-03-25](https://cloud.githubusercontent.com/assets/197788/21588166/248b6f00-d0f5-11e6-8c18-4a79eedfeafa.jpg)

From the EventViewer. Karabiner is **not* running.   I pressed MissionControl key (F3)
![eventviewer 2017-01-02 14-05-22](https://cloud.githubusercontent.com/assets/197788/21588181/4b29b590-d0f5-11e6-9de2-7d31f992e5fa.jpg)

From the EventViewer. Karabiner is **not** running.  I pressed Dashboard key (F4)
There are no events at all.

**Comment by tekezo** [comment]
@hostmaster Thank you for feedback.

# About f3 key
I'm confirmed that the key order is swapped with the hardware macro keys.
(eg. your f3 key which sends control+up)

I've fixed this issue at v0.90.73.

# About f4 key
I guess your f4 key sends f12 key event.
Please try this configuration.
![170104-0001](https://cloud.githubusercontent.com/assets/659178/21638878/9fd48360-d2b0-11e6-97de-2c91f09bd1b1.png)

**Comment by hostmaster** [comment]
@tekezo 0.90.73  MissionControl key (F3) works now. 

I made the change you have sugested. Dock key (f12) shows dock key still. f4 shows dashboard  with `dashboard` and with `launchpad` so probably it has no effect. 

F12 ![eventviewer 2017-01-04 13-58-38](https://cloud.githubusercontent.com/assets/197788/21640326/0a0f4966-d286-11e6-8179-742ee37222c4.jpg)

**Comment by tekezo** [comment]
The f12 key seems sending some key combination like f3 key.
Can you bind the key combination to your desired function in System Preferences > Keyboard > Shortcuts?

**Comment by hostmaster** [comment]
yes it is. you are right. however there are some issues still. 

Power button does not work on external keyboard. 
```
eventType:SysKeyDown      code:0x6        name:power           flags:                                   misc:
eventType:SysKeyUp        code:0x6        name:power           flags:                                   misc:
```

Multimedia keys do not work as well 
```
eventType:SysKeyDown      code:0x14       name:rewind          flags:                                   misc:
eventType:SysKeyUp        code:0x14       name:rewind          flags:                                   misc:
eventType:SysKeyDown      code:0x10       name:play_or_pause   flags:                                   misc:
eventType:SysKeyUp        code:0x10       name:play_or_pause   flags:                                   misc:
eventType:SysKeyDown      code:0x13       name:fastforward     flags:                                   misc:
eventType:SysKeyUp        code:0x13       name:fastforward     flags:                                   misc:
eventType:SysKeyDown      code:0x7        name:mute            flags:                                   misc:
eventType:SysKeyUp        code:0x7        name:mute            flags:                                   misc:
eventType:SysKeyDown      code:0x1        name:volume_decremen flags:                                   misc:
eventType:SysKeyUp        code:0x1        name:volume_decremen flags:                                   misc:
eventType:SysKeyDown      code:0x0        name:volume_incremen flags:                                   misc:
eventType:SysKeyUp        code:0x0        name:volume_incremen flags:                                   misc:
```

I recorded all these events when karabiner did not run. When KE runs EvenViewer is empty.

**Comment by reesd** [comment]
Karabiner Elements breaks all the function keys and Eject key on Logitech K760 also - #458

**Comment by qnub** [comment]
Keyboard Bloody B530R — multimedia key stop working with running KE

**Comment by Splaktar** [comment]
This is still an issue.

**Comment by Splaktar** [comment]
This is still an issue.
