### ISSUE TITLE
Keyboard completely stops working

### ISSUE THREAD

**Issue by carlca** [tekezo/Karabiner-Elements#769]
Apple Mac Pro (Early 2009)
Firmware upgraded from 4.1 to 5.1
Running macOS 10.12.5 Sierra
Was running Karibiner Elements - compiled from source - now deleted!
Apple Mac wired USB Keyboard

Hello, I suffered a problem whereby my keyboard totally stopped working a few days ago, and I had to spend time with Apple support, and eventually, it turned out that the only way to fix the problem was to create a new user account with all the attendant migration problems. 

I didn't connect the problem with Karabiner at the time and have spent the last couple of days rebuilding my system. I have just briefly fired up Karabiner again, and the fucking keyboard problem is back again. I've deleted Karabiner with AppCleaner and restarted the Apple Mac. Still, I have no keyboard.

I am furious. I've wasted 3 days of my life which I'm never going to get back. I know this was not officially released software but, all the same, I think I could reasonably expect the software not to destroy my keyboard usage.

I would like detailed instructions on how to fix my Apple Mac. Your software broke it. You, therefore, must have the ability to reverse the damage. I expect a reply immediately.

Thank you,
Carl Caulkett

**Comment by carlca** [comment]
I've just spent another 25 minutes removing all traces of Karabiner (it splatters itself all around the bloody system) in various config files. At last, my keyboard works again. I'm still angry, but not as angry when I thought I was going to have to spend another 2 days rebuilding my system again.

**Comment by carlca** [comment]
Christ! You make it difficult to remove your software. Spent half an hour getting rid of the Karabiner app and associated config files, only to find the App running on my Menu Bar and the config files have fucking reappeared. It's as bad as AVG software and that's saying something! Google have a motto "Do no evil!". I think you, as a company, should settle for the less ambitious, but equally worthy "Do no damage!".

**Comment by carlca** [comment]
It's now an hour later, and with the help of a genuinely helpful piece of software called Find Any File, I think I can say that I have removed any trace of Karabiner software. This has been an object lesson in the difference between "smart" software and "(too) clever (for its own good)" software. It's also a lesson in  "knowing the price of everything and the value of nothing". I'll leave you to work out which side of the equation I think you fall. Don't worry, unless your software rears its ugly head again, something that I haven't entirely ruled out happening again, you won't be hearing from me again.

**Comment by cmsj** [comment]
@carlca this is all completely unreasonable behaviour. Please report legitimate bugs with an attitude of collaboration - this is open source software, you didn't pay anything for it, if you want it to be better, you are part of the solution :)

**Comment by carlca** [comment]
I have wasted 3 days of my life, and have been facing a possible reinstall
of my Mac OS. I think I should be getting an apology from someone rather
than a lecture in the finer points of Github etiquette. You would be angry
too if put in the same circumstances. Don't try and take the moral high
ground here.

**Comment by carlca** [comment]
You would find, incidentally, that if I were to receive a sincere,
well-intentioned apology, my demeanour would transform as if by magic from
my current, admittedly grumpy persona, into a much more friendly and
forgiving, and yes, reasonable mood. I await with interest...

**Comment by cmsj** [comment]
My reply has little to do with GitHub etiquette and a lot more to do with basic human decency. I do not represent the Karabiner project, but it is wildly unreasonable of you to expect anything from people who choose to spend their free time building software that they then give away (including its source).

You had a bad experience with Karabiner, and I sympathise with the frustration you are feeling, but that doesn't mean anyone owes you an apology, and it is rude of you to attempt to make anyone feel bad for their hard work.

**Comment by carlca** [comment]
I think it is entirely reasonable to expect that software put out for
public consumption, whether paid for or free, at least is built on design
decisions which do not involve peppering the user's hard disk with an
unholy amount of config files, which make it very difficult to uninstall,
and I am not the only person, by far to have experienced these problems.

In case you forgot, this software which was intended to fix a keyboard
related shortcoming ended up rendering the entire keyboard inoperative.
"Epic Fail" as I believe the younger generation would put it.

The incident is bothering me less now. However, I do not believe that you
empathise with my situation one iota, and feel that it is you who has
entirely overstepped the mark in wading into a dispute that does not
directly concern you. And please spare me the condescending tripe about
"basic human decency", and do not dare to tell me what I was attempting to
make people feel.

As you say, you do not represent the Karabiner project so I will leave you
up there in the thin air of the moral high ground, and instead, wait to see
if the Karabiner folks put in an appearance. I wouldn't try to contact me
again, I won't reply. Over and out.

**Comment by cmsj** [comment]
"Karabiner folks" is pretty much one guy. One awesome guy who has spent a vast amount of time over the last *10 years* building Karabiner, and is now rebuilding it completely to work with the new kernel input layer that Sierra introduced.

Karabiner Elements is pre-1.0 software at the moment, and is undergoing a great deal of work to get it back even close to the featureset of Karabiner.

I'm not sure why you keep complaining about where it places files, when it has an Uninstaller on the Misc tab of its preferences, but perhaps something about the way you chose to build it made a difference, or didn't build the uninstaller tool.

I genuinely do empathise with your situation, I've used software before that has failed me spectacularly, and I too have made the mistake of being rude about it. I'm not on any high ground here trying to make myself seem infallible.

The real reason I am posting here, is not to talk to you, I'm talking to everyone else who comes across this issue, particularly anyone who contributes to Karabiner. I want to signal clearly that your entitled negativity is not going unchallenged, because such attitudes can be very demotivating to people who are choosing to spend their free time making other peoples' lives better.

I don't want someone to sit down and think "right, time to make Karabiner better", see an issue like this, and then think "actually, maybe I'll just read a book under a tree, people are awful".

**Comment by carlca** [comment]
Chris,

I built Karabiner-Elements entirely to the steps laid out in Github. I made
no non-standard decisions whatsoever. Be that as it may, I take your point
about how the awesome guy might feel, and believe me, as a fellow
programmer of 30 years standing, the last thing I would want to do is to
make him feel that it was all a waste of time.

I switched to using an Apple Mac 5 weeks ago and have been learning more
during that time than I have in the past 5 years and it's been like a
breath of fresh air. I'm not working at the moment, so I could barely
afford the machine (it was a reconditioned model, in case you were
wondering), and during the period of time when the keyboard wasn't working,
I went through the extreme stress of wondering whether I had wasted $700.
That is truly demotivating, I can tell you.

To then discover that it was due to a programming error that was so
fundamental (I keep coming back to the fact it was a keyboard utility that
screwed the keyboard), was intensely annoying. I would think that any
programmer worth his or her salt would be keen to find out about such a
problem, would be suitably apologetic, and would resolve to fix the issue.

I said I wouldn't reply, but your last email was sufficiently reasonable,
IMNSHO, that I felt compelled to respond once more, so kudos to you, Chris.

Cheers,
Carl

**Comment by cmsj** [comment]
❤️

**Comment by carlca** [comment]
Friends, again?

**Comment by dunkarooftop** [comment]
@cmsj and @carlca 

it's rare to see on internet, kudos to both of you !! 

to Chris
thank you for the hammerspoon project !!

to carlca
There is a wicked community around the mac automation. If you want to archive something and have a problem feel free to post questions. Assuming that you are coming from Windows world. Welcome to mac :)

**Comment by carlca** [comment]
@cmsj and @tekezo After a good night's sleep I've calmed right down. First of all, @tekezo my profound apologies if any of my words caused you distress. I let my anger run away with itself, never a good trait in anyone. @cmsj Chris apologies to you as well, same story really. At least we kept things civil and didn't resort to ranting and screaming! @dunkarooftop Yes! I'm crawling out, blinking and rubbing my eyes in amazement, as I behold the sun-kissed uplands of the Mac world (less poetry, please. Ed). Assuming I haven't blotted my copy book too much, I look forward to learning more about Mac automation. It's all so new and rather exciting! After 25 years of DLL hell, MSI misery and God knows whatever other Bill Gates inspired misery, I'm loving the Mac way of doing things. That's not to say that everything is going to be plain sailing, but hopefully, with the help of intelligent help provided by the likes of you, it shouldn't be too bad!

**Comment by carlca** [comment]
@cmsj Chris, I notice that you live in London. Whereabouts? I'm in Maida Vale, these days.

**Comment by cmsj** [comment]
@carlca Surbiton :)

**Comment by carlca** [comment]
Living The Good Life, eh? I did a day of door-to-door selling in Surbiton
once before I decided that that was not a good career move!

**Comment by dunkarooftop** [comment]
@carlca 
couple resources for you, apps that you will most likely to encounter alone the path
Launcher app: LaunchBar, Alfred (I would suggest Alfred because it's easy to make your own workflow without much coding)

Keyboard Maestro for all the macro

Hammerspoon by @cmsj 

Here is a good starting point
http://www.macautomationtips.com/

best luck : )

**Comment by nikitavoloboev** [comment]
Just wanted to drop in here to really say just how much @tekezo is really doing for this 'mac automation community'. What karabiner allows you to do is insane if you really go and study the private.xml and all of its options. And to then release this all for free and open the source code is incredibly generous. 

But I also sympathise with you @carlca, as I've been in your exact situation although not my keyboard was broken but karabiner stopped working which in my case is like saying that keyboard did not work. I actually went on to learn about C++  after this to perhaps try and understand some parts of the code and maybe contribute because this software has become so essential to my life. 

The only advice I can give is to really be proactive about these kinds of things and appreciate people's work and time that they have put into this project. 

I myself don't see myself moving to Sierra or High Sierra in any time soon because my karabiner config is [11k lines long](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml). :)

**Comment by tekezo** [comment]
Karbiner-Element 0.91.0 has this issue and I've fixed this issue in 0.91.1.

**Comment by carlca** [comment]
Thanks a lot @tekezo for fixing this so quickly, and once again please accept my sincere apologies for any negative comments I may have made. I now appreciate what a monumental job you have done, and the extent to which the Sierra OS update must have wrong-footed everyone!

Best wishes,
Car;

**Comment by paxperscientiam** [comment]
I think I am having the same issue as @carlca .

What happens is this:
* install Karabiner Elements
* Works great!
* Restart my computer
* Login
* Keyboard non-responsive
* Quit karabiner
* keyboard works again

The above holds true for the internal keyboard, bluetooth connected, and usb connected keyboards.

I've noticed another anomaly as well. After starting up the computer, logging in, and finding the keyboard non-responsive, I have see some graphical oddities. For instance, when in Finder, files remain highlighted as single click one, followed by another. May be not related.

**Comment by drummingdemon** [comment]
I have the same problem, although reconnecting the USB cable of the keyboard fixes the problem instantly even at the login screen and it remains in a connected state until the next reboot.

**Comment by hirett1** [comment]
Same issue here, awful piece of work. Exit the damn thing and the keyboard won't work. Ran an uninstall script, Karabiner disappeared but the keyboard still won't work, scared me to death because I didn't even have the damn thing anymore to run to get the keyboard back, restarted the computer and only then the keyboard came back on.

**Comment by carlca** [comment]
To be fair, after my initial scare, I re-installed the app a few months later and it has worked perfectly for me ever since.
