### ISSUE TITLE
Command key always pressed

### ISSUE THREAD

**Issue by staeke** [tekezo/Karabiner-Elements#824]
First, thanks for a great product and apologies for a rather vague possible bug report. 

**Sometimes** when my computer wakes up from sleep, it behaves as if the left command key is always pressed, with corresponding behavior. For instance, every link clicked on a web page opens in a new window. The only way to fix this is to restart the computer. I **think** this has not happened when I haven't used Karabiner Elements.

Is there any way of providing a manual "keyboard reset" command or similar? Alternatively call that automatically after waking up from sleep or starting the app?

**Comment by h-nn-ng** [comment]
Have to confirm that this is Karabiner issue. Just updated from 0.91.5 to 0.91.6 and had the same problem immediately and it took me a while to understand why every app behaves so weird. Rebooted once and the cmd key isn't pressed anymore.
Also: Thanks for this great app! 👍

**Comment by akira-okumura** [comment]
I have the same problem, but in my case it is not a command key but OS behaves as if a shift key is being pressed down.

I use macOS 10.12.5 (MacBook Pro (Retina, 15-inch, Mid 2014)) and Karabiner-Elements 0.91.6. I hope some information below is helpful for debugging.

1. My Settings
<img width="900" alt="screen shot 2017-07-12 at 21 29 09" src="https://user-images.githubusercontent.com/2981330/28117639-3b7e8dd8-6749-11e7-9a00-f368295dfaa3.png">
<img width="900" alt="screen shot 2017-07-12 at 21 29 13" src="https://user-images.githubusercontent.com/2981330/28117641-3ba83106-6749-11e7-87cf-414b8d18e7c2.png">

2. Quitting Karabiner-Elements immediately resolves the issue, that's why I believe this is a Karabiner-Elements issue.

3. I have never seen this problem with 0.91.5.

4. It looks to appear only after waking up from sleep.

5. I have checked key events by Karabiner-EventViewer. Pressing the left shift key properly shows event types "FlagsChanged 0x38 left_shift Shift" and "FlagsChanged 0x38 left_shift" sequentially.

6. In all applications, they behave as if a shift key is being pressed down, but in Japanese IME, I can type hiragana (pressing the left shift key usually changes the typed hiragana to katakana). So it is puzzling.

**Comment by apm1467** [comment]
Same problem for me in 0.91.6. The letter A is being pressed down after MacBook wakes up from sleep.

In EventViewer, it just shows a constant stream of letter A KeyDown.

I quitted Karabiner-Elements once, the problem still remains. Then I reopened and quitted Karabiner-Elements again, the problem suddenly goes away.

**Comment by alexeden** [comment]
I'm getting the same thing in 0.91.7.
It's happened 3 times since it started a couple days ago. If I open EventViewer and mash all the keyboard keys randomly (because desparation), it stops. 

I don't see any errors in the logs; just warnings:
```
[2017-07-13 21:15:47.511] [info] [console_user_server] core_configuration is updated.
[2017-07-13 21:15:47.511] [info] [console_user_server] Check for updates...
[2017-07-13 21:15:47.513] [info] [grabber] event_tap_manager initialized
[2017-07-13 21:15:47.513] [info] [grabber] Load karabiner.json...
[2017-07-13 21:15:47.513] [info] [grabber] core_configuration is updated.
[2017-07-13 21:15:47.514] [info] [grabber] initialize_virtual_hid_keyboard
[2017-07-13 21:15:47.514] [info] [grabber]   keyboard_type:40
[2017-07-13 21:15:47.514] [info] [grabber]   caps_lock_delay_milliseconds:0
[2017-07-13 21:15:47.514] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-07-13 21:15:47.514] [warning] [grabber] virtual_hid_keyboard is not ready. Please wait for a while.
[2017-07-13 21:15:47.515] [info] [grabber] matching device:
[2017-07-13 21:15:47.516] [info] [grabber]   manufacturer: pqrs.org
[2017-07-13 21:15:47.516] [info] [grabber]   product: Karabiner VirtualHIDKeyboard
[2017-07-13 21:15:47.516] [info] [grabber]   vendor_id: 0x0
[2017-07-13 21:15:47.516] [info] [grabber]   product_id: 0x0
[2017-07-13 21:15:47.516] [info] [grabber]   location_id: 0x0
[2017-07-13 21:15:47.516] [info] [grabber]   serial_number: org.pqrs.driver.Karabiner.VirtualHIDDevice.VirtualHIDKeyboard
[2017-07-13 21:15:47.516] [info] [grabber]   registry_entry_id: 4294982545
[2017-07-13 21:15:47.519] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:3) is detected.
[2017-07-13 21:15:47.519] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-07-13 21:15:47.669] [info] [console_user_server] frontmost_application_observer initialize
[2017-07-13 21:15:48.579] [info] [console_user_server] system_preferences::values is updated.
[2017-07-13 21:15:48.580] [info] [grabber] system_preferences_values_updated
[2017-07-13 21:15:48.580] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is grabbed
[2017-07-13 21:16:35.847] [info] [console_user_server] the configuration directory is updated.
[2017-07-13 21:16:35.875] [info] [console_user_server] the configuration directory is updated.
[2017-07-13 21:16:35.875] [info] [console_user_server] Check version...
[2017-07-13 21:16:35.876] [info] [console_user_server] Version is changed: '0.91.6' -> '0.91.7'
[2017-07-13 21:16:35.993] [info] [console_user_server] version 0.91.7
[2017-07-13 21:16:35.994] [info] [console_user_server] Check version...
[2017-07-13 21:16:36.257] [info] [grabber] version 0.91.7
[2017-07-13 21:16:36.259] [info] [grabber] Check version...
[2017-07-13 21:16:36.439] [info] [grabber] IOServiceOpen is succeeded @ void krbn::virtual_hid_device_client::matched_callback(io_iterator_t)
[2017-07-13 21:16:36.472] [info] [grabber] matching device:
[2017-07-13 21:16:36.472] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 21:16:36.472] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 21:16:36.472] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 21:16:36.472] [info] [grabber]   product_id: 0x274
[2017-07-13 21:16:36.472] [info] [grabber]   location_id: 0x14400000
[2017-07-13 21:16:36.472] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 21:16:36.472] [info] [grabber]   registry_entry_id: 4294968105
[2017-07-13 21:16:36.473] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is detected.
[2017-07-13 21:16:36.474] [info] [grabber] matching device:
[2017-07-13 21:16:36.474] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 21:16:36.474] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 21:16:36.474] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 21:16:36.474] [info] [grabber]   product_id: 0x274
[2017-07-13 21:16:36.474] [info] [grabber]   location_id: 0x14400000
[2017-07-13 21:16:36.474] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 21:16:36.474] [info] [grabber]   registry_entry_id: 4294968109
[2017-07-13 21:16:36.475] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is detected.
[2017-07-13 21:16:37.540] [info] [grabber] current_console_user_id: 502
[2017-07-13 21:16:37.540] [info] [grabber] Check version...
[2017-07-13 21:16:46.220] [info] [console_user_server] version 0.91.7
[2017-07-13 21:16:46.220] [info] [console_user_server] Check version...
[2017-07-13 21:16:47.297] [info] [console_user_server] receiver is initialized
[2017-07-13 21:16:47.297] [info] [console_user_server] Check version...
[2017-07-13 21:16:47.298] [info] [grabber] karabiner_console_user_server is connected (pid:25066)
[2017-07-13 21:16:47.298] [info] [console_user_server] grabber_client_ is connected
[2017-07-13 21:16:47.298] [info] [console_user_server] Load karabiner.json...
[2017-07-13 21:16:47.298] [info] [console_user_server] core_configuration is updated.
[2017-07-13 21:16:47.298] [info] [console_user_server] Check for updates...
[2017-07-13 21:16:47.300] [info] [grabber] event_tap_manager initialized
[2017-07-13 21:16:47.300] [info] [grabber] Load karabiner.json...
[2017-07-13 21:16:47.301] [info] [grabber] core_configuration is updated.
[2017-07-13 21:16:47.301] [info] [grabber] initialize_virtual_hid_keyboard
[2017-07-13 21:16:47.301] [info] [grabber]   keyboard_type:40
[2017-07-13 21:16:47.301] [info] [grabber]   caps_lock_delay_milliseconds:0
[2017-07-13 21:16:47.302] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-07-13 21:16:47.302] [warning] [grabber] virtual_hid_keyboard is not ready. Please wait for a while.
[2017-07-13 21:16:47.303] [info] [grabber] matching device:
[2017-07-13 21:16:47.303] [info] [grabber]   manufacturer: pqrs.org
[2017-07-13 21:16:47.303] [info] [grabber]   product: Karabiner VirtualHIDKeyboard
[2017-07-13 21:16:47.303] [info] [grabber]   vendor_id: 0x0
[2017-07-13 21:16:47.303] [info] [grabber]   product_id: 0x0
[2017-07-13 21:16:47.303] [info] [grabber]   location_id: 0x0
[2017-07-13 21:16:47.303] [info] [grabber]   serial_number: org.pqrs.driver.Karabiner.VirtualHIDDevice.VirtualHIDKeyboard
[2017-07-13 21:16:47.303] [info] [grabber]   registry_entry_id: 4294982605
[2017-07-13 21:16:47.305] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:3) is detected.
[2017-07-13 21:16:47.311] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-07-13 21:16:47.425] [info] [console_user_server] frontmost_application_observer initialize
[2017-07-13 21:16:48.371] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is grabbed
[2017-07-13 21:16:48.373] [info] [grabber] system_preferences_values_updated
[2017-07-13 21:16:48.373] [info] [console_user_server] system_preferences::values is updated.
[2017-07-13 22:26:59.943] [info] [grabber] version 0.91.7
[2017-07-13 22:26:59.950] [info] [grabber] Check version...
[2017-07-13 22:27:00.170] [info] [grabber] IOServiceOpen is succeeded @ void krbn::virtual_hid_device_client::matched_callback(io_iterator_t)
[2017-07-13 22:27:00.175] [info] [grabber] matching device:
[2017-07-13 22:27:00.175] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 22:27:00.175] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 22:27:00.175] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 22:27:00.175] [info] [grabber]   product_id: 0x274
[2017-07-13 22:27:00.175] [info] [grabber]   location_id: 0x14400000
[2017-07-13 22:27:00.175] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 22:27:00.175] [info] [grabber]   registry_entry_id: 4294968109
[2017-07-13 22:27:00.175] [info] [console_user_server] connection_manager::grabber_is_launched_callback
[2017-07-13 22:27:00.175] [info] [console_user_server] frontmost_application_observer terminate
[2017-07-13 22:27:00.176] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is detected.
[2017-07-13 22:27:00.177] [info] [grabber] matching device:
[2017-07-13 22:27:00.177] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 22:27:00.177] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 22:27:00.177] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 22:27:00.177] [info] [grabber]   product_id: 0x274
[2017-07-13 22:27:00.177] [info] [grabber]   location_id: 0x14400000
[2017-07-13 22:27:00.177] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 22:27:00.177] [info] [grabber]   registry_entry_id: 4294968105
[2017-07-13 22:27:00.178] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is detected.
[2017-07-13 22:27:01.055] [info] [console_user_server] receiver is terminated
[2017-07-13 22:27:01.059] [warning] [console_user_server] bind: No such file or directory
[2017-07-13 22:27:01.178] [info] [grabber] current_console_user_id: 502
[2017-07-13 22:27:01.178] [info] [grabber] Check version...
[2017-07-13 22:27:01.812] [info] [grabber] karabiner_console_user_server is connected (pid:25066)
[2017-07-13 22:27:01.812] [info] [console_user_server] receiver is initialized
[2017-07-13 22:27:01.812] [info] [console_user_server] Check version...
[2017-07-13 22:27:01.812] [info] [console_user_server] grabber_client_ is connected
[2017-07-13 22:27:01.812] [info] [console_user_server] Load karabiner.json...
[2017-07-13 22:27:01.812] [info] [console_user_server] core_configuration is updated.
[2017-07-13 22:27:01.812] [info] [console_user_server] Check for updates...
[2017-07-13 22:27:01.815] [info] [grabber] event_tap_manager initialized
[2017-07-13 22:27:01.815] [info] [grabber] Load karabiner.json...
[2017-07-13 22:27:01.815] [info] [grabber] core_configuration is updated.
[2017-07-13 22:27:01.815] [info] [grabber] initialize_virtual_hid_keyboard
[2017-07-13 22:27:01.815] [info] [grabber]   keyboard_type:40
[2017-07-13 22:27:01.815] [info] [grabber]   caps_lock_delay_milliseconds:0
[2017-07-13 22:27:01.816] [warning] [grabber] virtual_hid_keyboard is not ready. Please wait for a while.
[2017-07-13 22:27:01.816] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 22:27:01.817] [info] [grabber] matching device:
[2017-07-13 22:27:01.817] [info] [grabber]   manufacturer: pqrs.org
[2017-07-13 22:27:01.817] [info] [grabber]   product: Karabiner VirtualHIDKeyboard
[2017-07-13 22:27:01.817] [info] [grabber]   vendor_id: 0x0
[2017-07-13 22:27:01.817] [info] [grabber]   product_id: 0x0
[2017-07-13 22:27:01.817] [info] [grabber]   location_id: 0x0
[2017-07-13 22:27:01.817] [info] [grabber]   serial_number: org.pqrs.driver.Karabiner.VirtualHIDDevice.VirtualHIDKeyboard
[2017-07-13 22:27:01.817] [info] [grabber]   registry_entry_id: 4294982966
[2017-07-13 22:27:01.819] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:3) is detected.
[2017-07-13 22:27:01.820] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 22:27:01.957] [info] [console_user_server] frontmost_application_observer initialize
[2017-07-13 22:27:02.886] [info] [console_user_server] system_preferences::values is updated.
[2017-07-13 22:27:02.887] [info] [grabber] system_preferences_values_updated
[2017-07-13 22:27:02.887] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is grabbed
[2017-07-13 23:09:40.677] [info] [grabber] version 0.91.7
[2017-07-13 23:09:40.695] [info] [grabber] Check version...
[2017-07-13 23:09:41.230] [info] [grabber] IOServiceOpen is succeeded @ void krbn::virtual_hid_device_client::matched_callback(io_iterator_t)
[2017-07-13 23:09:41.241] [info] [grabber] matching device:
[2017-07-13 23:09:41.241] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 23:09:41.241] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 23:09:41.241] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 23:09:41.241] [info] [grabber]   product_id: 0x274
[2017-07-13 23:09:41.241] [info] [grabber]   location_id: 0x14400000
[2017-07-13 23:09:41.241] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 23:09:41.242] [info] [grabber]   registry_entry_id: 4294968109
[2017-07-13 23:09:41.242] [info] [console_user_server] connection_manager::grabber_is_launched_callback
[2017-07-13 23:09:41.242] [info] [console_user_server] frontmost_application_observer terminate
[2017-07-13 23:09:41.243] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is detected.
[2017-07-13 23:09:41.243] [info] [grabber] matching device:
[2017-07-13 23:09:41.243] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-13 23:09:41.243] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-13 23:09:41.243] [info] [grabber]   vendor_id: 0x5ac
[2017-07-13 23:09:41.243] [info] [grabber]   product_id: 0x274
[2017-07-13 23:09:41.243] [info] [grabber]   location_id: 0x14400000
[2017-07-13 23:09:41.243] [info] [grabber]   serial_number: D3H52374NA1FTV4AA3FS
[2017-07-13 23:09:41.243] [info] [grabber]   registry_entry_id: 4294968105
[2017-07-13 23:09:41.244] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is detected.
[2017-07-13 23:09:42.287] [info] [console_user_server] receiver is terminated
[2017-07-13 23:09:42.287] [warning] [console_user_server] bind: No such file or directory
[2017-07-13 23:09:42.304] [info] [grabber] current_console_user_id: 502
[2017-07-13 23:09:42.304] [info] [grabber] Check version...
[2017-07-13 23:09:42.707] [info] [grabber] karabiner_console_user_server is connected (pid:25066)
[2017-07-13 23:09:42.707] [info] [console_user_server] receiver is initialized
[2017-07-13 23:09:42.707] [info] [console_user_server] Check version...
[2017-07-13 23:09:42.707] [info] [console_user_server] grabber_client_ is connected
[2017-07-13 23:09:42.707] [info] [console_user_server] Load karabiner.json...
[2017-07-13 23:09:42.708] [info] [console_user_server] core_configuration is updated.
[2017-07-13 23:09:42.708] [info] [console_user_server] Check for updates...
[2017-07-13 23:09:42.709] [info] [grabber] event_tap_manager initialized
[2017-07-13 23:09:42.709] [info] [grabber] Load karabiner.json...
[2017-07-13 23:09:42.709] [info] [grabber] core_configuration is updated.
[2017-07-13 23:09:42.709] [info] [grabber] initialize_virtual_hid_keyboard
[2017-07-13 23:09:42.709] [info] [grabber]   keyboard_type:40
[2017-07-13 23:09:42.709] [info] [grabber]   caps_lock_delay_milliseconds:0
[2017-07-13 23:09:42.710] [warning] [grabber] virtual_hid_keyboard is not ready. Please wait for a while.
[2017-07-13 23:09:42.710] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 23:09:42.710] [info] [grabber] matching device:
[2017-07-13 23:09:42.711] [info] [grabber]   manufacturer: pqrs.org
[2017-07-13 23:09:42.711] [info] [grabber]   product: Karabiner VirtualHIDKeyboard
[2017-07-13 23:09:42.711] [info] [grabber]   vendor_id: 0x0
[2017-07-13 23:09:42.711] [info] [grabber]   product_id: 0x0
[2017-07-13 23:09:42.711] [info] [grabber]   location_id: 0x0
[2017-07-13 23:09:42.711] [info] [grabber]   serial_number: org.pqrs.driver.Karabiner.VirtualHIDDevice.VirtualHIDKeyboard
[2017-07-13 23:09:42.711] [info] [grabber]   registry_entry_id: 4294983146
[2017-07-13 23:09:42.713] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:3) is detected.
[2017-07-13 23:09:42.713] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 23:09:42.875] [info] [console_user_server] frontmost_application_observer initialize
[2017-07-13 23:09:43.782] [info] [grabber] system_preferences_values_updated
[2017-07-13 23:09:43.782] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is grabbed
[2017-07-13 23:09:43.782] [info] [console_user_server] system_preferences::values is updated.
[2017-07-13 23:10:59.621] [info] [grabber] Load karabiner.json...
[2017-07-13 23:10:59.621] [info] [console_user_server] Load karabiner.json...
[2017-07-13 23:10:59.623] [info] [grabber] core_configuration is updated.
[2017-07-13 23:10:59.623] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 23:10:59.623] [info] [console_user_server] core_configuration is updated.
[2017-07-13 23:11:55.034] [info] [grabber] Load karabiner.json...
[2017-07-13 23:11:55.034] [info] [console_user_server] Load karabiner.json...
[2017-07-13 23:11:55.036] [info] [grabber] core_configuration is updated.
[2017-07-13 23:11:55.036] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is ignored.
[2017-07-13 23:11:55.036] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 23:11:55.036] [info] [console_user_server] core_configuration is updated.
[2017-07-13 23:12:09.128] [info] [grabber] Load karabiner.json...
[2017-07-13 23:12:09.129] [info] [console_user_server] Load karabiner.json...
[2017-07-13 23:12:09.130] [info] [grabber] core_configuration is updated.
[2017-07-13 23:12:09.130] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:1) is ignored.
[2017-07-13 23:12:09.130] [info] [console_user_server] core_configuration is updated.
[2017-07-13 23:12:09.297] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is grabbed
```

**Comment by tekezo** [comment]
Thank you for feedback!
I believe this issue has been fixed at the latest version. (v0.91.8)
Please confirm v0.91.8.

I guess this issue is caused by karabiner_grabber process crash that is fixed at v0.91.8.
(I think there are some crash logs in Console.app.)

**Comment by akira-okumura** [comment]
Hi @tekezo 

Thank you for the update, but I encountered this problem again this morning. In my case it is always the (left?) option key. I rebooted Karabiner-Elements several times but it didn't help at this time, while I reported before that rebooting Karabiner-Elements temporality resolved the issue.

I typed the right option key, which is changed to be a function key in my environment, finding that it fixed my problem. As I have shown in a previous post with screen shots, I use "right_option to fn." Perhaps this setting is related to my option key problem.

I do not see any output in the Log tab or Console.app when the problem appeared.

いつも更新ありがとうございます。以前に Karabiner-Elements を再起動すると治ると書いたのですが、勘違いだったかたまたまだったのかもしれません。0.91.8 を再起動しても、sleep 後に option が押されっぱなしの状態になる問題は解決されず、右側の option (fn に置き換え済み) を押すと症状が治りました。

どこか debug 情報など取得すべきものがあれば、次回問題が再発した時に情報を集めますので、ご指示ください。

**Comment by staeke** [comment]
Got it again now. Using 0.91.8 Here's an excerpt from the log. I basically had it shutdown between 18:39 yesterday and 08:59 today.

```
[2017-07-17 18:39:10.636] [info] [grabber] removal device:
[2017-07-17 18:39:10.636] [info] [grabber]   vendor_id: 0x45e
[2017-07-17 18:39:10.636] [info] [grabber]   product_id: 0x745
[2017-07-17 18:39:10.636] [info] [grabber]   location_id: 0x14130000
[2017-07-17 18:39:10.659] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:10) is removed.
[2017-07-17 18:39:10.753] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:11) is ignored.
[2017-07-17 18:39:10.753] [info] [grabber] Staffan Eketorp’s Trackpad (device_id:9) is ignored.
[2017-07-17 18:39:10.753] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 18:39:10.760] [info] [grabber] removal device:
[2017-07-17 18:39:10.760] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 18:39:10.760] [info] [grabber]   product_id: 0x250
[2017-07-17 18:39:10.760] [info] [grabber]   location_id: 0x14120000
[2017-07-17 18:39:10.760] [info] [grabber] Apple Keyboard (device_id:13) is removed.
[2017-07-17 18:39:10.771] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:11) is ignored.
[2017-07-17 18:39:10.771] [info] [grabber] Staffan Eketorp’s Trackpad (device_id:9) is ignored.
[2017-07-17 18:39:10.771] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 18:39:10.771] [info] [grabber] removal device:
[2017-07-17 18:39:10.771] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 18:39:10.771] [info] [grabber]   product_id: 0xffff
[2017-07-17 18:39:10.771] [info] [grabber]   location_id: 0x14130000
[2017-07-17 18:39:10.771] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:12) is removed.
[2017-07-17 18:39:10.777] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:11) is ignored.
[2017-07-17 18:39:10.777] [info] [grabber] Staffan Eketorp’s Trackpad (device_id:9) is ignored.
[2017-07-17 18:39:10.777] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 18:39:10.778] [info] [grabber] removal device:
[2017-07-17 18:39:10.778] [info] [grabber]   vendor_id: 0x45e
[2017-07-17 18:39:10.778] [info] [grabber]   product_id: 0x745
[2017-07-17 18:39:10.778] [info] [grabber]   location_id: 0x14130000
[2017-07-17 18:39:10.778] [info] [grabber] Microsoft® Nano Transceiver v2.0 (device_id:11) is removed.
[2017-07-17 18:39:10.800] [info] [grabber] Staffan Eketorp’s Trackpad (device_id:9) is ignored.
[2017-07-17 18:39:10.800] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 18:52:01.244] [info] [grabber] removal device:
[2017-07-17 18:52:01.244] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 18:52:01.244] [info] [grabber]   product_id: 0x30e
[2017-07-17 18:52:01.244] [info] [grabber]   location_id: 0x3539f6d9
[2017-07-17 18:52:01.245] [info] [grabber] Staffan Eketorp’s Trackpad (device_id:9) is removed.
[2017-07-17 18:52:02.329] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 23:40:27.220] [info] [grabber] removal device:
[2017-07-17 23:40:27.760] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 23:40:27.760] [info] [grabber]   product_id: 0x274
[2017-07-17 23:40:27.760] [info] [grabber]   location_id: 0x14400000
[2017-07-17 23:40:27.760] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:2) is removed.
[2017-07-17 23:40:28.301] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is ignored.
[2017-07-17 23:40:28.304] [info] [grabber] removal device:
[2017-07-17 23:40:28.304] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 23:40:28.304] [info] [grabber]   product_id: 0x274
[2017-07-17 23:40:28.304] [info] [grabber]   location_id: 0x14400000
[2017-07-17 23:40:28.304] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:7) is removed.
[2017-07-17 23:40:28.307] [info] [grabber] matching device:
[2017-07-17 23:40:28.307] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-17 23:40:28.307] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-17 23:40:28.307] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 23:40:28.307] [info] [grabber]   product_id: 0x274
[2017-07-17 23:40:28.308] [info] [grabber]   location_id: 0x14400000
[2017-07-17 23:40:28.308] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-17 23:40:28.308] [info] [grabber]   registry_entry_id: 4294999566
[2017-07-17 23:40:28.311] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:14) is detected.
[2017-07-17 23:40:28.311] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:14) is ignored.
[2017-07-17 23:40:28.312] [info] [grabber] matching device:
[2017-07-17 23:40:28.312] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-17 23:40:28.312] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-17 23:40:28.312] [info] [grabber]   vendor_id: 0x5ac
[2017-07-17 23:40:28.312] [info] [grabber]   product_id: 0x274
[2017-07-17 23:40:28.312] [info] [grabber]   location_id: 0x14400000
[2017-07-17 23:40:28.312] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-17 23:40:28.312] [info] [grabber]   registry_entry_id: 4294999562
[2017-07-17 23:40:28.315] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:15) is detected.
[2017-07-17 23:40:28.315] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:14) is ignored.
[2017-07-17 23:40:28.549] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:15) is grabbed
[2017-07-18 01:40:38.617] [info] [grabber] removal device:
[2017-07-18 01:40:40.145] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 01:40:40.145] [info] [grabber]   product_id: 0x274
[2017-07-18 01:40:40.145] [info] [grabber]   location_id: 0x14400000
[2017-07-18 01:40:40.145] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:15) is removed.
[2017-07-18 01:40:40.244] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:14) is ignored.
[2017-07-18 01:40:40.247] [info] [grabber] removal device:
[2017-07-18 01:40:40.247] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 01:40:40.247] [info] [grabber]   product_id: 0x274
[2017-07-18 01:40:40.247] [info] [grabber]   location_id: 0x14400000
[2017-07-18 01:40:40.247] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:14) is removed.
[2017-07-18 01:40:40.250] [info] [grabber] matching device:
[2017-07-18 01:40:40.250] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 01:40:40.250] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 01:40:40.250] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 01:40:40.250] [info] [grabber]   product_id: 0x274
[2017-07-18 01:40:40.250] [info] [grabber]   location_id: 0x14400000
[2017-07-18 01:40:40.250] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 01:40:40.250] [info] [grabber]   registry_entry_id: 4294999747
[2017-07-18 01:40:40.354] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:16) is detected.
[2017-07-18 01:40:40.356] [info] [grabber] matching device:
[2017-07-18 01:40:40.356] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 01:40:40.356] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 01:40:40.356] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 01:40:40.356] [info] [grabber]   product_id: 0x274
[2017-07-18 01:40:40.356] [info] [grabber]   location_id: 0x14400000
[2017-07-18 01:40:40.356] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 01:40:40.356] [info] [grabber]   registry_entry_id: 4294999757
[2017-07-18 01:40:40.359] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:17) is detected.
[2017-07-18 01:40:40.360] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:17) is ignored.
[2017-07-18 01:40:40.461] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:16) is grabbed
[2017-07-18 03:40:52.350] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:16) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 03:40:52.765] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:16) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 03:40:52.765] [info] [grabber] removal device:
[2017-07-18 03:40:52.765] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 03:40:52.765] [info] [grabber]   product_id: 0x274
[2017-07-18 03:40:52.765] [info] [grabber]   location_id: 0x14400000
[2017-07-18 03:40:52.765] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:16) is removed.
[2017-07-18 03:40:53.244] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:17) is ignored.
[2017-07-18 03:40:53.245] [info] [grabber] removal device:
[2017-07-18 03:40:53.245] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 03:40:53.245] [info] [grabber]   product_id: 0x274
[2017-07-18 03:40:53.245] [info] [grabber]   location_id: 0x14400000
[2017-07-18 03:40:53.245] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:17) is removed.
[2017-07-18 03:40:53.433] [info] [grabber] matching device:
[2017-07-18 03:40:53.433] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 03:40:53.433] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 03:40:53.433] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 03:40:53.433] [info] [grabber]   product_id: 0x274
[2017-07-18 03:40:53.433] [info] [grabber]   location_id: 0x14400000
[2017-07-18 03:40:53.433] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 03:40:53.433] [info] [grabber]   registry_entry_id: 4294999980
[2017-07-18 03:40:53.717] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:18) is detected.
[2017-07-18 03:40:53.719] [info] [grabber] matching device:
[2017-07-18 03:40:53.719] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 03:40:53.719] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 03:40:53.719] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 03:40:53.719] [info] [grabber]   product_id: 0x274
[2017-07-18 03:40:53.719] [info] [grabber]   location_id: 0x14400000
[2017-07-18 03:40:53.719] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 03:40:53.719] [info] [grabber]   registry_entry_id: 4294999991
[2017-07-18 03:40:53.722] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:19) is detected.
[2017-07-18 03:40:53.724] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:19) is ignored.
[2017-07-18 03:40:53.896] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:18) is grabbed
[2017-07-18 05:41:05.453] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:18) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 05:41:05.683] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:18) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 05:41:05.683] [info] [grabber] removal device:
[2017-07-18 05:41:05.683] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 05:41:05.683] [info] [grabber]   product_id: 0x274
[2017-07-18 05:41:05.683] [info] [grabber]   location_id: 0x14400000
[2017-07-18 05:41:05.683] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:18) is removed.
[2017-07-18 05:41:05.749] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:19) is ignored.
[2017-07-18 05:41:05.750] [info] [grabber] removal device:
[2017-07-18 05:41:05.750] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 05:41:05.750] [info] [grabber]   product_id: 0x274
[2017-07-18 05:41:05.750] [info] [grabber]   location_id: 0x14400000
[2017-07-18 05:41:05.750] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:19) is removed.
[2017-07-18 05:41:05.755] [info] [grabber] matching device:
[2017-07-18 05:41:05.755] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 05:41:05.755] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 05:41:05.755] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 05:41:05.755] [info] [grabber]   product_id: 0x274
[2017-07-18 05:41:05.755] [info] [grabber]   location_id: 0x14400000
[2017-07-18 05:41:05.756] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 05:41:05.756] [info] [grabber]   registry_entry_id: 4295000191
[2017-07-18 05:41:05.761] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:20) is detected.
[2017-07-18 05:41:05.794] [info] [grabber] matching device:
[2017-07-18 05:41:05.794] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 05:41:05.794] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 05:41:05.794] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 05:41:05.794] [info] [grabber]   product_id: 0x274
[2017-07-18 05:41:05.794] [info] [grabber]   location_id: 0x14400000
[2017-07-18 05:41:05.794] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 05:41:05.794] [info] [grabber]   registry_entry_id: 4295000195
[2017-07-18 05:41:05.820] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:21) is detected.
[2017-07-18 05:41:05.821] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:21) is ignored.
[2017-07-18 05:41:06.071] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:20) is grabbed
[2017-07-18 06:40:36.595] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:20) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 06:40:37.289] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:20) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 06:40:37.289] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:20) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 06:40:37.289] [info] [grabber] removal device:
[2017-07-18 06:40:37.289] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 06:40:37.289] [info] [grabber]   product_id: 0x274
[2017-07-18 06:40:37.289] [info] [grabber]   location_id: 0x14400000
[2017-07-18 06:40:37.289] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:20) is removed.
[2017-07-18 06:40:37.736] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:21) is ignored.
[2017-07-18 06:40:37.736] [info] [grabber] removal device:
[2017-07-18 06:40:37.736] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 06:40:37.736] [info] [grabber]   product_id: 0x274
[2017-07-18 06:40:37.736] [info] [grabber]   location_id: 0x14400000
[2017-07-18 06:40:37.736] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:21) is removed.
[2017-07-18 06:40:37.895] [info] [grabber] matching device:
[2017-07-18 06:40:37.895] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 06:40:37.895] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 06:40:37.895] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 06:40:37.895] [info] [grabber]   product_id: 0x274
[2017-07-18 06:40:37.895] [info] [grabber]   location_id: 0x14400000
[2017-07-18 06:40:37.895] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 06:40:37.895] [info] [grabber]   registry_entry_id: 4295000450
[2017-07-18 06:40:38.067] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:22) is detected.
[2017-07-18 06:40:38.120] [info] [grabber] matching device:
[2017-07-18 06:40:38.120] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 06:40:38.120] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 06:40:38.120] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 06:40:38.120] [info] [grabber]   product_id: 0x274
[2017-07-18 06:40:38.120] [info] [grabber]   location_id: 0x14400000
[2017-07-18 06:40:38.120] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 06:40:38.120] [info] [grabber]   registry_entry_id: 4295000460
[2017-07-18 06:40:38.121] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:23) is detected.
[2017-07-18 06:40:38.178] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:23) is ignored.
[2017-07-18 06:40:38.386] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:22) is grabbed
[2017-07-18 08:57:53.369] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:22) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 08:57:54.043] [error] [grabber] IOHIDDeviceSetValue error -536870206 for Apple Internal Keyboard / Trackpad (device_id:22) @ ___ZN4krbn22human_interface_device23set_caps_lock_led_stateENS_9led_stateE_block_invoke
[2017-07-18 08:57:54.043] [info] [grabber] removal device:
[2017-07-18 08:57:54.043] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 08:57:54.043] [info] [grabber]   product_id: 0x274
[2017-07-18 08:57:54.043] [info] [grabber]   location_id: 0x14400000
[2017-07-18 08:57:54.043] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:22) is removed.
[2017-07-18 08:57:54.168] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:23) is ignored.
[2017-07-18 08:57:54.169] [info] [grabber] removal device:
[2017-07-18 08:57:54.169] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 08:57:54.169] [info] [grabber]   product_id: 0x274
[2017-07-18 08:57:54.169] [info] [grabber]   location_id: 0x14400000
[2017-07-18 08:57:54.169] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:23) is removed.
[2017-07-18 08:57:54.171] [info] [grabber] matching device:
[2017-07-18 08:57:54.171] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 08:57:54.171] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 08:57:54.171] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 08:57:54.171] [info] [grabber]   product_id: 0x274
[2017-07-18 08:57:54.171] [info] [grabber]   location_id: 0x14400000
[2017-07-18 08:57:54.171] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 08:57:54.171] [info] [grabber]   registry_entry_id: 4295000690
[2017-07-18 08:57:54.174] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:24) is detected.
[2017-07-18 08:57:54.267] [info] [grabber] matching device:
[2017-07-18 08:57:54.267] [info] [grabber]   manufacturer: Apple Inc.
[2017-07-18 08:57:54.267] [info] [grabber]   product: Apple Internal Keyboard / Trackpad
[2017-07-18 08:57:54.267] [info] [grabber]   vendor_id: 0x5ac
[2017-07-18 08:57:54.267] [info] [grabber]   product_id: 0x274
[2017-07-18 08:57:54.267] [info] [grabber]   location_id: 0x14400000
[2017-07-18 08:57:54.267] [info] [grabber]   serial_number: D3H53957UE1FTV4A06FS
[2017-07-18 08:57:54.267] [info] [grabber]   registry_entry_id: 4295000698
[2017-07-18 08:57:54.268] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:25) is detected.
[2017-07-18 08:57:54.284] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:25) is ignored.
[2017-07-18 08:57:54.454] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:24) is grabbed
[2017-07-18 08:59:17.003] [info] [grabber] Load karabiner.json...
[2017-07-18 08:59:17.027] [info] [grabber] core_configuration is updated.
[2017-07-18 08:59:17.029] [info] [grabber] initialize_virtual_hid_keyboard
[2017-07-18 08:59:17.029] [info] [grabber]   keyboard_type:40
[2017-07-18 08:59:17.029] [info] [grabber]   caps_lock_delay_milliseconds:0
[2017-07-18 08:59:17.029] [info] [console_user_server] Load karabiner.json...
[2017-07-18 08:59:17.031] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:25) is ignored.
[2017-07-18 08:59:17.031] [warning] [grabber] virtual_hid_keyboard is not ready. Please wait for a while.
[2017-07-18 08:59:17.031] [info] [grabber] removal device:
[2017-07-18 08:59:17.031] [info] [grabber]   vendor_id: 0x0
[2017-07-18 08:59:17.031] [info] [grabber]   product_id: 0x0
[2017-07-18 08:59:17.031] [info] [grabber]   location_id: 0x0
[2017-07-18 08:59:17.031] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:8) is removed.
[2017-07-18 08:59:17.031] [info] [console_user_server] core_configuration is updated.
[2017-07-18 08:59:17.032] [info] [grabber] Connected devices are ungrabbed
[2017-07-18 08:59:17.033] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:25) is ignored.
[2017-07-18 08:59:17.033] [info] [grabber] matching device:
[2017-07-18 08:59:17.033] [info] [grabber]   manufacturer: pqrs.org
[2017-07-18 08:59:17.033] [info] [grabber]   product: Karabiner VirtualHIDKeyboard
[2017-07-18 08:59:17.033] [info] [grabber]   vendor_id: 0x0
[2017-07-18 08:59:17.033] [info] [grabber]   product_id: 0x0
[2017-07-18 08:59:17.033] [info] [grabber]   location_id: 0x0
[2017-07-18 08:59:17.033] [info] [grabber]   serial_number: org.pqrs.driver.Karabiner.VirtualHIDDevice.VirtualHIDKeyboard
[2017-07-18 08:59:17.034] [info] [grabber]   registry_entry_id: 4295000936
[2017-07-18 08:59:17.037] [info] [grabber] Karabiner VirtualHIDKeyboard (device_id:26) is detected.
[2017-07-18 08:59:17.037] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:25) is ignored.
[2017-07-18 08:59:18.109] [info] [grabber] Apple Internal Keyboard / Trackpad (device_id:24) is grabbed
```

**Comment by apm1467** [comment]
I think I get the reason now.

@akira-okumura uses the Emacs key bindings, which map `option + b/f` to `option + arrow keys` like this:

```
{
  "type": "basic",
  "from": <%= from("b", ["option"], ["caps_lock", "shift"]) %>,
  "to": <%= to([["left_arrow", ["left_option"]]]) %>,
  "conditions": [ <%= frontmost_application_unless("emacs_key_bindings_exception") %> ]
},
```

However, the Emacs key bindings do not append a `vk_none` key after the `left_arrow + left_option` event, so the `left_option` modifier will keep pressed after this event. Append a `vk_none` in this rule should fix the problem:

```
"to": <%= to([["left_arrow", ["left_option"]], ["vk_none"]]) %>,
```

Other complex modification rules may have this same problem. Every time a modifier key has been mapped to, we must manually append a `vk_none` after that event to release the modifier key.

**Comment by apm1467** [comment]
No, actually we should use `to_after_key_up` to release the modifier key, so if the user keeps pressing `option + b`, he will get the multiple `left_arrow` strokes as expected.

```
{
  "type": "basic",
  "from": <%= from("b", ["option"], ["caps_lock", "shift"]) %>,
  "to": <%= to([["left_arrow", ["left_option"]]]) %>,
  "to_after_key_up": <%= to([["vk_none"]]) %>,
  "conditions": [ <%= frontmost_application_unless("emacs_key_bindings_exception") %> ]
},
```

**Comment by tekezo** [comment]
First, please confirm the latest Karabiner-Elements. I fixed an issue about modifier flag handling in v0.91.11.

There are several layers related with input events. (Hardware, macOS system, Karabiner-Elements)
If restarting KE does not solve your issue, the issue is caused by hardware or macOS.

@apm1467 The lazy modifier flag release is necessary to suppress unnecessary flag changes.
For example, press control+p, control+n with emacs key bindings,

We want to send these events:
* control key down
* control key up
* up arrow key down
* up arrow key up
* down arrow key down
* down arrow key up

Without the lazy modifier flag release:
* control key down
* control key up
* up arrow key down
* up arrow key up
* control key down
* control key up
* down arrow key down
* down arrow key up
* up arrow key down

**Comment by akira-okumura** [comment]
I have used 0.91.11 and 0.91.12 for a while, but I still have this issue. Repeating restart of KE several times usually fixes this issue.

**Comment by akira-okumura** [comment]
Duplicate to #466

**Comment by apm1467** [comment]
@akira-okumura Would you mind test [this modified version of Emacs key bindings](https://yige.ch/static/emacs_key_bindings_vk_none.json)? 

You can just disable the official Emacs key bindings, copy this JSON file to `~/.config/karabiner/assets/complex_modifications` and enable it in KE. All key bindings are the same.

I just append some `vk_none` after the option key bindings. As @tekezo has mentioned, this will create unnecessary flag changes. But as I've tested, it actually does not influence the normal usage. And it might fix the option key issue.

Hope it works.

**Comment by k0nserv** [comment]
I'm also seeing this on 0.91.12. Restarting Karabiner Elements resolves it for me

**Comment by tphalp** [comment]
KE Version: 0.91.12
MacOS: 10.12.6

Same thing here,  with the `Shift` key. It doesn't happen after every "sleep", but does happen enough that it is annoying. Quiting and Relaunching karabiner-elements usually, fixes it, but sometimes it takes a few quit/restarts to fix it.

The log file will be filled with these types of errors:

```
2017-08-09 09:54:21.695] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:21.696] [error] [grabber] IOHIDDeviceSetValue error -536870195 for Apple Keyboard (device_id:12) @ IOReturn krbn::human_interface_device::set_caps_lock_led_state(krbn::led_state)_block_invoke
[2017-08-09 09:54:21.793] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:21.894] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:21.994] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.094] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.192] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.294] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.393] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.493] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.590] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
[2017-08-09 09:54:22.696] [error] [grabber] IOHIDDeviceOpen error: kIOReturnBadArgument (-536870206) Apple Keyboard (device_id:12)
```

It adds about 10 lines of errors every second, until I quit KE, and relaunch.

**Comment by panozzaj** [comment]
I ran into this as well, my shift key was being held down so using a web browser in a normal way was quite challenging. I am guessing that this will be solved by me changing my (custom) readline-ish bindings in some way. I tried restarting KE but this didn't seem to solve the problem.

One thing that did seem to remove the key from being held down was invoking a few of my custom bindings. I am guessing that it ended up running them and then sending `VK_NONE` as specified to clear the shift key. Now I am able to use apps normally! I realize this is just a workaround but it might be helpful for someone.
